### ISSUE TITLE
Running mvn install on clean clone fails

### ISSUE THREAD

**Issue by TruffleMuffin** [awslabs/aws-codebuild-jenkins-plugin#5]
The tests are failing preventing the compilation from completing. This appears to be due to missing dependant resources.

```Running CodeBuilderEndToEndPerformTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.08 sec - in CodeBuilderConfigurationTest
Running CodeBuilderHelperTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 sec - in CodeBuilderHelperTest
Running CodeBuilderPerformTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.048 sec - in CodeBuilderPerformTest
Running ProjectFactoryTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.078 sec - in ProjectFactoryTest
Running S3DataManagerTest
Tests run: 11, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 1.594 sec <<< FAILURE! - in S3DataManagerTest
testZipSourceDoubleDirMultipleHugeFiles(S3DataManagerTest)  Time elapsed: 0.064 sec  <<< ERROR!
java.lang.Exception: zipSource usage: prefixToTrim must be contained in the given directory.
        at S3DataManager.zipSource(S3DataManager.java:117)
        at S3DataManager.zipSource(S3DataManager.java:131)
        at S3DataManagerTest.testZipSourceDoubleDirMultipleHugeFiles(S3DataManagerTest.java:351)

testZipSourceOneDirEmpty(S3DataManagerTest)  Time elapsed: 0.007 sec  <<< ERROR!
java.lang.Exception: zipSource usage: prefixToTrim must be contained in the given directory.
        at S3DataManager.zipSource(S3DataManager.java:117)
        at S3DataManager.zipSource(S3DataManager.java:131)
        at S3DataManagerTest.testZipSourceOneDirEmpty(S3DataManagerTest.java:200)

testUploadSource(S3DataManagerTest)  Time elapsed: 1.241 sec  <<< ERROR!
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1911)
        at S3DataManager.uploadSourceToS3(S3DataManager.java:66)
        at S3DataManagerTest.testUploadSource(S3DataManagerTest.java:116)

testZipSourceMultipleNestedDirs(S3DataManagerTest)  Time elapsed: 0.013 sec  <<< ERROR!
java.lang.Exception: zipSource usage: prefixToTrim must be contained in the given directory.
        at S3DataManager.zipSource(S3DataManager.java:117)
        at S3DataManager.zipSource(S3DataManager.java:131)
        at S3DataManagerTest.testZipSourceMultipleNestedDirs(S3DataManagerTest.java:413)

testZipSourceOneDir(S3DataManagerTest)  Time elapsed: 0.014 sec  <<< ERROR!
java.lang.Exception: zipSource usage: prefixToTrim must be contained in the given directory.
        at S3DataManager.zipSource(S3DataManager.java:117)
        at S3DataManager.zipSource(S3DataManager.java:131)
        at S3DataManagerTest.testZipSourceOneDir(S3DataManagerTest.java:232)

testZipSourceOneDirMultipleFiles(S3DataManagerTest)  Time elapsed: 0.014 sec  <<< ERROR!
java.lang.Exception: zipSource usage: prefixToTrim must be contained in the given directory.
        at S3DataManager.zipSource(S3DataManager.java:117)
        at S3DataManager.zipSource(S3DataManager.java:131)
        at S3DataManagerTest.testZipSourceOneDirMultipleFiles(S3DataManagerTest.java:286)

Running UtilsTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in UtilsTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 44.325 sec - in CodeBuilderEndToEndPerformTest

Results :

Tests in error:
  S3DataManagerTest.testZipSourceDoubleDirMultipleHugeFiles:351 ╗  zipSource usa...
  S3DataManagerTest.testZipSourceOneDirEmpty:200 ╗  zipSource usage: prefixToTri...
  S3DataManagerTest.testUploadSource:116 ╗ StringIndexOutOfBounds String index o...
  S3DataManagerTest.testZipSourceMultipleNestedDirs:413 ╗  zipSource usage: pref...
  S3DataManagerTest.testZipSourceOneDir:232 ╗  zipSource usage: prefixToTrim mus...
  S3DataManagerTest.testZipSourceOneDirMultipleFiles:286 ╗  zipSource usage: pre...

Tests run: 42, Failures: 0, Errors: 6, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:12 min
[INFO] Finished at: 2016-12-15T12:25:16+00:00
[INFO] Final Memory: 24M/158M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test (default-test) on project aws-codebuild: There are test failures.
[ERROR]
[ERROR] Please refer to c:\Production\Packages\aws-codebuild-jenkins-plugin\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by TruffleMuffin** [comment]
This happens on a windows box.

**Comment by taoyong-ty** [comment]
Just pushed a fix for this https://github.com/awslabs/aws-codebuild-jenkins-plugin/commit/3864b2c66630fc7a84196d2d5e3158ed43e224e7
