### ISSUE TITLE
support withAWS assume role 

### ISSUE THREAD

**Issue by samdammers** [awslabs/aws-codebuild-jenkins-plugin#61]
Hi team,

Apologies if I have missed how to accomplish this, but it appears using Assume Role is not supported as the AWS_SESSION_TOKEN is not being sent with the request when specifying the awsAccessKey and awsSecretKeys?

Our CI server lives in account X and is assuming the cicd role in Account Y
I have confirmed that the permissions are all fine by printing out the keys/token and testing via the command line.

Can we add support for STS Assume roles?

Pipeline code below:
```
            withAWS(region: params.AWS_REGION, role: cicdRoleName, roleAccount: awsAccountId) {     
                codeBuildResult = awsCodeBuild projectName: config.repoName,
                    region: params.AWS_REGION,
                    sourceControlType: 'project',
                    credentialsType: 'keys',
                    awsAccessKey: env.AWS_ACCESS_KEY_ID,
                    awsSecretKey: env.AWS_SECRET_ACCESS_KEY,
                    envVariables: "${codebuildEnvVars}"
            }
```

Jenkins Error:
```
[Pipeline] awsCodeBuild
00:00:12.128 [AWS CodeBuild Plugin] Using given AWS access and secret key for authorization
00:00:12.278 [AWS CodeBuild Plugin] The security token included in the request is invalid. (Service: AWSCodeBuild; Status Code: 400; Error Code: UnrecognizedClientException; Request ID: 36dab899-4f28-11e8-90d9-891f23967dfc)
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

CodeBuildException
	at CodeBuildStep$CodeBuildExecution.run(CodeBuildStep.java:286)
	at CodeBuildStep$CodeBuildExecution.run(CodeBuildStep.java:249)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

**Comment by leobaran-aws** [comment]
Thanks for letting us know about this use case. Have you tried using a set of CodeBuild credentials? They have IAM Role support. Giving an option to manually specify the session token would integrate better with the `withAWS` syntax in your pipeline, however. I'll mark this as a feature request.

**Comment by samdammers** [comment]
I haven't tried using the CodeBuild creds, We use federated IDP for user access and do not provision local IAM user.  Thanks for the quick reply we will implement a workaround in the mean time.

**Comment by leobaran-aws** [comment]
I didn't hear back from @b-b3rn4rd in the pull request, but I made a minor change and pushed it in 32f5a78e9db195e7a595a3f4b606d6c5931e5acf. Thanks for the feedback--I'm glad we could get this use case working.

**Comment by leobaran-aws** [comment]
@b-b3rn4rd @samdammers This change was released in version 0.25 of the plugin

**Comment by lkolchin** [comment]
Hi,

Seems like I'm having the same issue.
I thought you guys resolved it.
Or maybe I'm using "withAWS" wrong with your plugin?

```
                        withAWS(region: 'ap-southeast-2', role: 'CodeBuildWithJenkinsServiceRole', roleAccount: '123456789123', externalId: '123456-2c1a-4367-aa09-123456') {
                            sh 'aws ssm get-parameter --name "/github-codebuild/github/token"'
                            try {
                            cbResult = awsCodeBuild projectName: 'rds-for-pretokengen-lambda',
                                sourceControlType: 'project',
                                credentialsType: 'keys',
                                awsAccessKey: env.AWS_ACCESS_KEY_ID,
                                awsSecretKey: env.AWS_SECRET_ACCESS_KEY,
                                region: 'ap-southeast-2',
                                envVariables: '[ { GITHUB_OWNER, company }, { GITHUB_REPO, rds-for-pretokengen-lambda } ]',
                                artifactTypeOverride: 'S3', 
                                artifactLocationOverride: 'githubcodebuild-artifacts',
                                overrideArtifactName: 'True'
                            } catch (Exception cbEx) {
                                cbResult = cbEx.getCodeBuildResult()
                            }
                        }
```

Getting this error:

```
[Pipeline] awsCodeBuild
[AWS CodeBuild Plugin] Using given AWS access and secret key for authorization
[AWS CodeBuild Plugin] The security token included in the request is invalid. (Service: AWSCodeBuild; Status Code: 400; Error Code: UnrecognizedClientException; Request ID: 361b1373-5638-41df-bddc-81dd53078beb; Proxy: )
```

So, essentially I'm running Jenkins master in  container on Fargate.

I've added the following perms to container's task role (I think that should suffice as those are exactly the same I've used in the User's attached poly - the user creds I've used to kick start Codebuild jobs) - Cloudformation style:
```
  ECSPassRoleCodebuild:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: !Sub "${AWS::StackName}-passrole-codebuild"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowPassRoleCodebuild
            Action:
              - "iam:PassRole"
            Effect: Allow
            Resource:
              - "*"

  ECSCodebuildPerms:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: !Sub "${AWS::StackName}-codebuild-perms"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - "codebuild:StartBuild"
              - "codebuild:BatchGetBuilds"
              - "codebuild:BatchGetProjects"
            Effect: Allow
            Resource:
              - "arn:aws:codebuild:ap-southeast-2:123456789123:project/*"
          - Effect: Allow
            Resource:
              - "arn:aws:logs:ap-southeast-2:123456789123:log-group:/aws/codebuild/*:*"
              - "arn:aws:logs:ap-southeast-2:123456789123:log-group:/aws/codebuild/*"
            Action:
              - logs:GetLogEvents
              - logs:FilterLogEvents
          - Effect: Allow
            Resource:
              - "arn:aws:s3:::githubcodebuildartifacts"
            Action:
              - "s3:GetBucketVersioning"
          - Effect: Allow
            Resource:
              - "arn:aws:s3:::githubcodebuildartifacts/*"
            Action:
              - "s3:PutObject"
          - Effect: Allow
            Resource:
              - "arn:aws:s3:::githubcodebuildartifacts/*"
            Action:
              - "s3:GetObject"
          - Effect: Allow
            Resource:
              - "arn:aws:codebuild:ap-southeast-2:123456789123:project/*"
            Action:
              - "codebuild:StartBuild"
              - "codebuild:BatchGetBuilds"
              - "codebuild:BatchGetProjects"
```

**Comment by lkolchin** [comment]
I actually looked at the PR you've mentioned above(Just after I've finished writing the comment above) - https://github.com/jenkinsci/aws-codebuild-plugin/pull/8
And then figured that "awsSessionToken: env.AWS_SESSION_TOKEN" was missing.
Now it's working!
Thank you :)

Can you please document this config in the plugin description?
It was a pain to find the right config :(

**Comment by leoherran-aws** [comment]
Updated README a6c535575fd76f37a361099899cf13fca961af86
