### ISSUE TITLE
NullPointerException after upgrade to 0.25

### ISSUE THREAD

**Issue by justinfalk** [awslabs/aws-codebuild-jenkins-plugin#65]
Hi,

I recently upgraded to version 0.25 and subsequently received a build failure with the message below.  Downgrading to 0.17 allowed the build to successfully complete.  Is there something I need to update in my config due to non-backwards compatible updaets?  This is a really simple config, using instance role rather than specifying credentials in jenkins. 

```
No emails were triggered.
[AWS CodeBuild Plugin] Using credentials provided by the DefaultAWSCredentialsProviderChain for authorization
ERROR: Build step failed with exception
java.lang.NullPointerException
	at CodeBuilder.logStartBuildMessage(CodeBuilder.java:523)
	at CodeBuilder.perform(CodeBuilder.java:318)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1794)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'AWS CodeBuild' marked build as failure
```

![jenkins](https://user-images.githubusercontent.com/16879499/41601598-7e7b7968-739e-11e8-97a3-71cde8d7a250.png)

**Comment by leobaran-aws** [comment]
Thanks for bringing this issue to our attention. Version 0.25 is supposed to backward compatible, but the plugin is not handling values of new attributes for older projects like yours. As a workaround, configure and save your project after installing version 0.25. We will work on a fix in the meantime.
