### ISSUE TITLE
no public field ‘cacheModeOverride’ (or getter method) found in class CodeBuildStep

### ISSUE THREAD

**Issue by akshaysgithub** [awslabs/aws-codebuild-jenkins-plugin#99]
Hello,

When I am using Snippet Generator in codebuild to generate codebuild script, I am getting the following error. I tried all options in cachemodeoverride, but it's not working out. I am using jenkins lts version. Basically docker run jenkins/jenkins:lts

Error log : 
```

WARNING o.j.p.workflow.cps.Snippetizer#doGenerateSnippet: failed to render {"includeUser": "false", "credentialsId": "", "credentialsType": "keys", "p
roxyHost": "", "proxyPort": "", "awsAccessKey": "", "awsSecretKey": "", "$redact": "awsSecretKey", "region": "eu-central-1", "projectName": "Supplier-Service-Develop", "sourceControlType": "
project", "sourceTypeOverride": "", "sourceLocationOverride": "", "sourceVersion": "", "gitCloneDepthOverride": "", "reportBuildStatusOverride": "", "sseAlgorithm": "", "localSourcePath": ""
, "workspaceSubdir": "", "artifactTypeOverride": "", "artifactLocationOverride": "", "artifactNameOverride": "", "overrideArtifactName": "", "artifactNamespaceOverride": "", "artifactPackagi
ngOverride": "", "artifactPathOverride": "", "artifactEncryptionDisabledOverride": "", "secondaryArtifactsOverride": "", "": ["", "", "", ""], "buildSpecFile": "", "environmentTypeOverride":
 "", "imageOverride": "", "privilegedModeOverride": "", "insecureSslOverride": "", "secondarySourcesOverride": "", "secondarySourcesVersionOverride": "", "computeTypeOverride": "", "cacheTyp
eOverride": "", "cacheLocationOverride": "", "cacheModesOverride": "", "cloudWatchLogsStatusOverride": "", "cloudWatchLogsGroupNameOverride": "", "cloudWatchLogsStreamNameOverride": "", "s3L
ogsStatusOverride": "", "s3LogsEncryptionDisabledOverride": "", "s3LogsLocationOverride": "", "certificateOverride": "", "serviceRoleOverride": "", "envVariables": "", "envParameters": "", "
buildTimeoutOverride": "", "cwlStreamingDisabled": "", "exceptionFailureMode": "", "downloadArtifacts": false, "downloadArtifactsRelativePath": "", "stapler-class": "CodeBuildStep", "$class"
: "CodeBuildStep"}
java.lang.UnsupportedOperationException: no public field ‘cacheModeOverride’ (or getter method) found in class CodeBuildStep
        at org.jenkinsci.plugins.structs.describable.DescribableParameter.getValue(DescribableParameter.java:161)
        at org.jenkinsci.plugins.structs.describable.DescribableParameter.inspect(DescribableParameter.java:142)
        at org.jenkinsci.plugins.structs.describable.DescribableModel.uninstantiate2(DescribableModel.java:655)
        at org.jenkinsci.plugins.structs.describable.DescribableModel.uninstantiate2_(DescribableModel.java:752)
        at org.jenkinsci.plugins.workflow.steps.StepDescriptor.uninstantiate(StepDescriptor.java:252)
        at org.jenkinsci.plugins.workflow.cps.Snippetizer.object2Groovy(Snippetizer.java:152)
        at org.jenkinsci.plugins.workflow.cps.Snippetizer.step2Groovy(Snippetizer.java:81)
        at org.jenkinsci.plugins.workflow.cps.Snippetizer.doGenerateSnippet(Snippetizer.java:526)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
        at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)

```

Plugin version 0.49. Any ideas?

**Comment by leoherran-aws** [comment]
Thanks for letting us know about this, we're looking into it and will have an update shortly.

**Comment by akshaysgithub** [comment]
> Thanks for letting us know about this, we're looking into it and will have an update shortly.

I went through the issue. As far as I understand, it's a spelling mistake. It should be cacheModeOverride, instead it's cacheModesOverride.

**Comment by leoherran-aws** [comment]
That's what I thought as well, but there isn't actually any instance of `cacheModeOverride` in the code. I'll update this issue when I find the root cause.
